FROM nginx:1.28.0

COPY default.conf /etc/nginx/conf.d/default.conf

WORKDIR /var/www/html

# Copy app code so Nginx can serve public assets and share same paths with PHP
COPY backend/ /var/www/html/

