name: OIDC debug and AWS configure

on:
  push:
    branches: [ "**" ]    # どのブランチでも実行（mainだけにしたいなら ["main"]）
  pull_request:            # PR 実行もテスト
  workflow_dispatch:       # 手動実行

permissions:
  id-token: write          # ← 必須（OIDCトークン発行）
  contents: read

jobs:
  debug-and-configure:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show basic GitHub context
        run: |
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          echo "GITHUB_REF=$GITHUB_REF"
          echo "GITHUB_HEAD_REF=$GITHUB_HEAD_REF"
          echo "GITHUB_EVENT_NAME=$GITHUB_EVENT_NAME"

      - name: Install jq (for parsing JSON)
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Dump OIDC token claims (audience=sts.amazonaws.com)
        shell: bash
        run: |
          set -euo pipefail

          # audience=sts.amazonaws.com の OIDC ID トークンを取得
          RAW_TOKEN="$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r '.value')"

          # JWT の payload をデコード
          PAYLOAD="$(echo "$RAW_TOKEN" | awk -F. '{print $2}' | base64 -d 2>/dev/null || true)"

          echo "=== OIDC payload (decoded) ==="
          echo "$PAYLOAD" | jq .

          echo "=== Hints ==="
          echo "iss / aud / sub を信頼ポリシーと一致させてください。"
          echo " - aud は通常 'sts.amazonaws.com'"
          echo " - sub 例:"
          echo "   * ブランチ: repo:hc100/vibe-coding-playground:ref:refs/heads/main"
          echo "   * PR:       repo:hc100/vibe-coding-playground:pull_request"
          echo "   * Env:      repo:hc100/vibe-coding-playground:environment:prod"
          echo "   * Reusable: repo:hc100/vibe-coding-playground:workflow_ref:hc100/vibe-coding-playground/.github/workflows/FILE.yml@refs/heads/main"

      - name: Configure AWS credentials (assume role via OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::331134574228:role/GitHubActions-LightsailDeployRole
          aws-region: ap-northeast-1

      - name: Verify caller identity
        run: aws sts get-caller-identity
