name: Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

permissions:          # ← これ超重要（ジョブ or ワークフローのいずれかに必須）
  id-token: write     # OIDC トークン発行に必要
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: main  # Environments を使うなら指定
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::331134574228:role/GitHubActions-LightsailDeployRole
          aws-region: ${{ vars.AWS_REGION }}

      - name: Who am I?
        run: aws sts get-caller-identity
