permissions:
  id-token: write
  contents: read

steps:
  - name: Dump OIDC token claims
    shell: bash
    run: |
      set -euo pipefail
      # audience=sts.amazonaws.com のトークンを取得
      RAW_TOKEN="$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
        "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r '.value')"

      # JWT の payload をデコードして表示
      PAYLOAD="$(echo "$RAW_TOKEN" | awk -F. '{print $2}' | base64 -d 2>/dev/null || true)"
      echo "=== OIDC payload ==="
      echo "$PAYLOAD" | jq .
  - name: Configure AWS creds (will fail, but after we saw claims)
    uses: aws-actions/configure-aws-credentials@v4
    with:
      role-to-assume: arn:aws:iam::331134574228:role/GitHubActions-LightsailDeployRole
      aws-region: ap-northeast-1
